version: '3.8'

x-api-config: &api-config
  build: .
  depends_on:
    postgres-node-1:
      condition: service_healthy

x-postgres-healthcheck: &postgres-healthcheck
  healthcheck:
    interval: 5s
    timeout: 10s
    retries: 10
    test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]

services:

  api-node-1:
    container_name: api-node-1
    <<: [ *api-config ]
    stdin_open: true
    tty: true
    env_file:
      - .env
#docker-compose exec -i api-node-1  java -jar application.jar
  postgres-node-1:
    image: 'postgres:16.1'
    container_name: postgres-node-1
    <<: *postgres-healthcheck
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres-node-1-data:/var/lib/postgresql/data