logging:
  level:
    root: info

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    default-schema: monitoring_schema
    liquibase-schema: migration_schema
    change-log: db.changelog/db.changelog-master.xml
  security:

jwt:
  secret: 6D597133743677397A24432646294A404E635166546A576E5A72347537782141
  token:
    expiration: 3600000

